In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/2023-spring-nlp-lab3-problem1/classification_class.pred.csv
/kaggle/input/datadata/classification_datasets/test_set.csv
/kaggle/input/datadata/classification_datasets/train_set.csv
/kaggle/input/datadata/classification_datasets/glove_word.json


# TRAIN_FILE

In [2]:
train_file = pd.read_csv("/kaggle/input/datadata/classification_datasets/train_set.csv", index_col = 0)

train_file, type(train_file)

(                                               sentence  label
 0     Cortez goodness Englishmen principle prenatal ...      1
 1     Cortez Falklands affect legend Terrified chief...      5
 2     Cortez Falklands whisky Stairway resources cha...      5
 3     vermicilli Protestant daughter whisky Sinclair...      4
 4     Kathie whisky Periodic subject yet adding Phil...      5
 ...                                                 ...    ...
 4995  Cortez Degas Englishmen murdering mess Casper ...      1
 4996  Cortez Robin Make-up Surveyor Madilyn might pr...      0
 4997               Kathie Robin foods within Bros. Noah      0
 4998  roulette titled Englishmen Presidents 007 IRL ...      3
 4999  San folk Panther disease will Will Philip addi...      0
 
 [5000 rows x 2 columns],
 pandas.core.frame.DataFrame)

In [3]:
import nltk
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

nltk.download('punkt') # Download the required punkt tokenizer
nltk.download('wordnet') # Download the required WordNet corpus

train_file = pd.read_csv("/kaggle/input/datadata/classification_datasets/train_set.csv", index_col = 0)

# Tokenize the sentences in the 'sentence' column of the train_file DataFrame
train_file['tokenized_sentence'] = train_file['sentence'].apply(word_tokenize)

# Print the first 5 rows of the DataFrame with tokenized sentences
train_file

[nltk_data] Downloading package punkt to /usr/share/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to /usr/share/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


sentence  label  \
0     Cortez goodness Englishmen principle prenatal ...      1   
1     Cortez Falklands affect legend Terrified chief...      5   
2     Cortez Falklands whisky Stairway resources cha...      5   
3     vermicilli Protestant daughter whisky Sinclair...      4   
4     Kathie whisky Periodic subject yet adding Phil...      5   
...                                                 ...    ...   
4995  Cortez Degas Englishmen murdering mess Casper ...      1   
4996  Cortez Robin Make-up Surveyor Madilyn might pr...      0   
4997               Kathie Robin foods within Bros. Noah      0   
4998  roulette titled Englishmen Presidents 007 IRL ...      3   
4999  San folk Panther disease will Will Philip addi...      0   

                                     tokenized_sentence  
0     [Cortez, goodness, Englishmen, principle, pren...  
1     [Cortez, Falklands, affect, legend, Terrified,...  
2     [Cortez, Falklands, whisky, Stairway, resource...  
3     [vermicilli, Protestant, daughter, whisky, Sin...  
4     [Kathie, whisky, Periodic, subject, yet, addin...  
...                                                 ...  
4995  [Cortez, Degas, Englishmen, murdering, mess, C...  
4996  [Cortez, Robin, Make-up, Surveyor, Madilyn, mi...  
4997        [Kathie, Robin, foods, within, Bros., Noah]  
4998  [roulette, titled, Englishmen, Presidents, 007...  
4999  [San, folk, Panther, disease, will, Will, Phil...  

[5000 rows x 3 columns]

In [4]:
!unzip -o /usr/share/nltk_data/corpora/wordnet.zip -d /usr/share/nltk_data/corpora/

Archive:  /usr/share/nltk_data/corpora/wordnet.zip
   creating: /usr/share/nltk_data/corpora/wordnet/
  inflating: /usr/share/nltk_data/corpora/wordnet/lexnames  
  inflating: /usr/share/nltk_data/corpora/wordnet/data.verb  
  inflating: /usr/share/nltk_data/corpora/wordnet/index.adv  
  inflating: /usr/share/nltk_data/corpora/wordnet/adv.exc  
  inflating: /usr/share/nltk_data/corpora/wordnet/index.verb  
  inflating: /usr/share/nltk_data/corpora/wordnet/cntlist.rev  
  inflating: /usr/share/nltk_data/corpora/wordnet/data.adj  
  inflating: /usr/share/nltk_data/corpora/wordnet/index.adj  
  inflating: /usr/share/nltk_data/corpora/wordnet/LICENSE  
  inflating: /usr/share/nltk_data/corpora/wordnet/citation.bib  
  inflating: /usr/share/nltk_data/corpora/wordnet/noun.exc  
  inflating: /usr/share/nltk_data/corpora/wordnet/verb.exc  
  inflating: /usr/share/nltk_data/corpora/wordnet/README  
  inflating: /usr/share/nltk_data/corpora/wordnet/index.sense  
  inflating: /usr/share/nltk_data

In [5]:
lemmatizer = WordNetLemmatizer()

# Lemmatize the tokenized sentences in the 'tokenized_sentence' column
train_file['lemmatized_sentence'] = train_file['tokenized_sentence'].apply(lambda x: [lemmatizer.lemmatize(word) for word in x])

# Print the first 5 rows of the DataFrame with lemmatized sentences

train_file['lemmatized_sentence'].values

array([list(['Cortez', 'goodness', 'Englishmen', 'principle', 'prenatal', 'symbolize', 'sword', 'Shia', 'Led', 'Noah']),
       list(['Cortez', 'Falklands', 'affect', 'legend', 'Terrified', 'chiefly', 'belong', 'bloom', '1935', 'Noah']),
       list(['Cortez', 'Falklands', 'whisky', 'Stairway', 'resource', 'chance', 'jeroboam', 'dummy', 'Bros.', 'Bullwinkle', 'adding', 'Darius', 'Noah']),
       ..., list(['Kathie', 'Robin', 'food', 'within', 'Bros.', 'Noah']),
       list(['roulette', 'titled', 'Englishmen', 'Presidents', '007', 'IRL', 'bloom', 'attends', 'Noah']),
       list(['San', 'folk', 'Panther', 'disease', 'will', 'Will', 'Philip', 'adding', 'bulb', 'resident', 'Noah'])],
      dtype=object)

# Max_length Sentence(20)_train_file

In [6]:
import numpy as np

data = train_file['lemmatized_sentence'].values # 데이터 배열

max_words = 20 # 최대 단어 개수     # 문장 길이

# 배열의 각 요소에서 20개의 단어만 선택하는 함수
def select_words(arr):
    return [word for word in arr[:max_words]]

# 배열의 각 요소에서 20개의 단어만 선택하는 코드
new_data = np.array([select_words(arr) if len(arr) > max_words else arr for arr in data], dtype=object)
new_data


max_len = max(len(lst) for lst in new_data)      # 가장 긴 리스트의 길이
new_data, max_len

(array([list(['Cortez', 'goodness', 'Englishmen', 'principle', 'prenatal', 'symbolize', 'sword', 'Shia', 'Led', 'Noah']),
        list(['Cortez', 'Falklands', 'affect', 'legend', 'Terrified', 'chiefly', 'belong', 'bloom', '1935', 'Noah']),
        list(['Cortez', 'Falklands', 'whisky', 'Stairway', 'resource', 'chance', 'jeroboam', 'dummy', 'Bros.', 'Bullwinkle', 'adding', 'Darius', 'Noah']),
        ..., list(['Kathie', 'Robin', 'food', 'within', 'Bros.', 'Noah']),
        list(['roulette', 'titled', 'Englishmen', 'Presidents', '007', 'IRL', 'bloom', 'attends', 'Noah']),
        list(['San', 'folk', 'Panther', 'disease', 'will', 'Will', 'Philip', 'adding', 'bulb', 'resident', 'Noah'])],
       dtype=object),
 20)

In [7]:
new_data

array([list(['Cortez', 'goodness', 'Englishmen', 'principle', 'prenatal', 'symbolize', 'sword', 'Shia', 'Led', 'Noah']),
       list(['Cortez', 'Falklands', 'affect', 'legend', 'Terrified', 'chiefly', 'belong', 'bloom', '1935', 'Noah']),
       list(['Cortez', 'Falklands', 'whisky', 'Stairway', 'resource', 'chance', 'jeroboam', 'dummy', 'Bros.', 'Bullwinkle', 'adding', 'Darius', 'Noah']),
       ..., list(['Kathie', 'Robin', 'food', 'within', 'Bros.', 'Noah']),
       list(['roulette', 'titled', 'Englishmen', 'Presidents', '007', 'IRL', 'bloom', 'attends', 'Noah']),
       list(['San', 'folk', 'Panther', 'disease', 'will', 'Will', 'Philip', 'adding', 'bulb', 'resident', 'Noah'])],
      dtype=object)

In [8]:
tuple_data = new_data.tolist()
#a = sum(tuple_data , [])

tuple_data[0:3]


[['Cortez',
  'goodness',
  'Englishmen',
  'principle',
  'prenatal',
  'symbolize',
  'sword',
  'Shia',
  'Led',
  'Noah'],
 ['Cortez',
  'Falklands',
  'affect',
  'legend',
  'Terrified',
  'chiefly',
  'belong',
  'bloom',
  '1935',
  'Noah'],
 ['Cortez',
  'Falklands',
  'whisky',
  'Stairway',
  'resource',
  'chance',
  'jeroboam',
  'dummy',
  'Bros.',
  'Bullwinkle',
  'adding',
  'Darius',
  'Noah']]

In [9]:
max_len = 20
pad_token = '[PAD]'
num_data = len(new_data)
new_data_padded = []
for sentence in new_data:
    if len(sentence) < max_len:
        num_padding = max_len - len(sentence)
        sentence = [pad_token] * num_padding + sentence
    else:
        sentence = sentence[:max_len]
    new_data_padded.append(sentence)
    
new_data_padded[0:2], np.array(new_data_padded).shape 

([['[PAD]',
   '[PAD]',
   '[PAD]',
   '[PAD]',
   '[PAD]',
   '[PAD]',
   '[PAD]',
   '[PAD]',
   '[PAD]',
   '[PAD]',
   'Cortez',
   'goodness',
   'Englishmen',
   'principle',
   'prenatal',
   'symbolize',
   'sword',
   'Shia',
   'Led',
   'Noah'],
  ['[PAD]',
   '[PAD]',
   '[PAD]',
   '[PAD]',
   '[PAD]',
   '[PAD]',
   '[PAD]',
   '[PAD]',
   '[PAD]',
   '[PAD]',
   'Cortez',
   'Falklands',
   'affect',
   'legend',
   'Terrified',
   'chiefly',
   'belong',
   'bloom',
   '1935',
   'Noah']],
 (5000, 20))

In [10]:
train_data = new_data_padded
train_data[0:2]#, train_data.shape

#train_data = train_data[0:2]

#train_data

[['[PAD]',
  '[PAD]',
  '[PAD]',
  '[PAD]',
  '[PAD]',
  '[PAD]',
  '[PAD]',
  '[PAD]',
  '[PAD]',
  '[PAD]',
  'Cortez',
  'goodness',
  'Englishmen',
  'principle',
  'prenatal',
  'symbolize',
  'sword',
  'Shia',
  'Led',
  'Noah'],
 ['[PAD]',
  '[PAD]',
  '[PAD]',
  '[PAD]',
  '[PAD]',
  '[PAD]',
  '[PAD]',
  '[PAD]',
  '[PAD]',
  '[PAD]',
  'Cortez',
  'Falklands',
  'affect',
  'legend',
  'Terrified',
  'chiefly',
  'belong',
  'bloom',
  '1935',
  'Noah']]

# DICTIONARY

In [11]:
import json

with open('/kaggle/input/datadata/classification_datasets/glove_word.json', 'r') as f:   # word to vec dictionary

    json_data = json.load(f)

#print(json.dumps(json_data))

# print(json_data)

#dic = pd.read_csv("/kaggle/input/datadata/classification_datasets/glove_word.json")
dic = json_data

#len(list(dic.values())[0])

#dic.values()


# Pretrained_embeddings

#X_train, X_train.shape
emb = np.array(list(dic.values()))

#b = a[X_train]

#b.shape



In [12]:
idx = list(range(0,len(dic)))

dic_list = list(dic.keys())

id_to_word = dict(zip(idx, dic_list))

word_to_id = {i: w for w, i in id_to_word.items()}
#word_to_id






In [13]:
len(dic)

9225

In [14]:
len(train_data)

5000

# Train_dataset(Word to idx(int))

In [15]:
# 일련번호 데이터
train_inputs = []
for s in train_data:                                 ##### 문장별 반복
    #print(s)
    #print("print SSSSS")
    row= []
    for w in s:
        #print(w)
        #print("WWWWWWWWW")
        if w in word_to_id:
            row.append(word_to_id[w])
            #print(row)
        else:
            row.append(word_to_id['[UNK]'])
    #print(row)                                    ##### 번호 나열
    train_inputs.append(row)
train_inputs = np.array(train_inputs)

train_inputs, train_inputs.shape

X_train = train_inputs
X_train

array([[   0,    0,    0, ..., 3212, 1461, 4942],
       [   0,    0,    0, ..., 2031, 2023, 4942],
       [   0,    0,    0, ..., 4940, 6956, 4942],
       ...,
       [   0,    0,    0, ..., 7796, 4495, 4942],
       [   0,    0,    0, ..., 2031, 1382, 4942],
       [   0,    0,    0, ...,    1, 4113, 4942]])

# TEST_FILE

In [16]:
test_file = pd.read_csv("/kaggle/input/datadata/classification_datasets/test_set.csv")

test_file, type(test_file)

(                                              sentence
 0    Cortez titled Englishmen delegation Falklands ...
 1    Cortez Phillip whisky Gutenberg iron-covered e...
 2    Cortez Degas Englishmen Spaghetti-o touring Ca...
 3    Cortez whisky Englishmen Dyck Casper skunks Wo...
 4    roulette whisky non-contagious Conception stol...
 ..                                                 ...
 447  Cortez Peloponnesian Degas Ridder bloom Line w...
 448  van Corporal Monopoly adding Troop East Florid...
 449        roulette Degas crayon bloom Die safari Noah
 450  Cortez Streetcar Crimean Michaelangelo Nations...
 451  Cortez Degas Englishmen Future Motto entertain...
 
 [452 rows x 1 columns],
 pandas.core.frame.DataFrame)

In [17]:
test_file = pd.read_csv("/kaggle/input/datadata/classification_datasets/test_set.csv")

# Tokenize the sentences in the 'sentence' column of the train_file DataFrame
test_file['tokenized_sentence'] = test_file['sentence'].apply(word_tokenize)

# Print the first 5 rows of the DataFrame with tokenized sentences
#test_file

In [18]:
lemmatizer = WordNetLemmatizer()

# Lemmatize the tokenized sentences in the 'tokenized_sentence' column
test_file['lemmatized_sentence'] = test_file['tokenized_sentence'].apply(lambda x: [lemmatizer.lemmatize(word) for word in x])

# Print the first 5 rows of the DataFrame with lemmatized sentences

#test_file['lemmatized_sentence'].values

In [19]:
import numpy as np

data = test_file['lemmatized_sentence'].values # 데이터 배열

max_words = 20 # 최대 단어 개수     # 문장 길이

# 배열의 각 요소에서 20개의 단어만 선택하는 함수
def select_words(arr):
    return [word for word in arr[:max_words]]

# 배열의 각 요소에서 20개의 단어만 선택하는 코드
new_data = np.array([select_words(arr) if len(arr) > max_words else arr for arr in data], dtype=object)
new_data


max_len = max(len(lst) for lst in new_data)      # 가장 긴 리스트의 길이
#new_data, max_len

In [20]:
tuple_data = new_data.tolist()

In [21]:
max_len = 20
pad_token = '[PAD]'
num_data = len(new_data)
new_data_padded = []
for sentence in new_data:
    if len(sentence) < max_len:
        num_padding = max_len - len(sentence)
        sentence = [pad_token] * num_padding + sentence
    else:
        sentence = sentence[:max_len]
    new_data_padded.append(sentence)
    
new_data_padded[0:2], np.array(new_data_padded).shape 

([['[PAD]',
   '[PAD]',
   '[PAD]',
   '[PAD]',
   '[PAD]',
   '[PAD]',
   '[PAD]',
   'Cortez',
   'titled',
   'Englishmen',
   'delegation',
   'Falklands',
   'adding',
   'Pass',
   'bronze',
   'singing',
   '007',
   'bloom',
   'Define',
   'Noah'],
  ['[PAD]',
   '[PAD]',
   '[PAD]',
   '[PAD]',
   '[PAD]',
   '[PAD]',
   '[PAD]',
   '[PAD]',
   '[PAD]',
   '[PAD]',
   '[PAD]',
   'Cortez',
   'Phillip',
   'whisky',
   'Gutenberg',
   'iron-covered',
   'exclusively',
   'dialing',
   'global',
   'Noah']],
 (452, 20))

In [22]:
test_data = new_data_padded

In [23]:
# 일련번호 데이터
test_inputs = []
for s in test_data:                                 ##### 문장별 반복
    #print(s)
    #print("print SSSSS")
    row= []
    for w in s:
        #print(w)
        #print("WWWWWWWWW")
        if w in word_to_id:
            row.append(word_to_id[w])
            #print(row)
        else:
            row.append(word_to_id['[UNK]'])
    #print(row)                                    ##### 번호 나열
    test_inputs.append(row)
test_inputs = np.array(test_inputs)

test_inputs[0], test_inputs.shape

X_test = test_inputs
X_test

array([[   0,    0,    0, ..., 2031, 5719, 4942],
       [   0,    0,    0, ..., 4054, 2962, 4942],
       [   0,    0,    0, ..., 1490, 4451, 4942],
       ...,
       [   0,    0,    0, ..., 1971, 8927, 4942],
       [   0,    0,    0, ...,  521, 1009, 4942],
       [   0,    0,    0, ..., 3998, 6090, 4942]])

# LABLE

In [24]:
y = pd.get_dummies(train_file['label']).values
y, y.shape

y_train = y
y_train, y_train.shape

(array([[0, 1, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 1],
        [0, 0, 0, 0, 0, 1],
        ...,
        [1, 0, 0, 0, 0, 0],
        [0, 0, 0, 1, 0, 0],
        [1, 0, 0, 0, 0, 0]], dtype=uint8),
 (5000, 6))

# DATA_shape

In [25]:
X_train, X_train.shape, X_test, X_test.shape, y_train, y_train.shape

(array([[   0,    0,    0, ..., 3212, 1461, 4942],
        [   0,    0,    0, ..., 2031, 2023, 4942],
        [   0,    0,    0, ..., 4940, 6956, 4942],
        ...,
        [   0,    0,    0, ..., 7796, 4495, 4942],
        [   0,    0,    0, ..., 2031, 1382, 4942],
        [   0,    0,    0, ...,    1, 4113, 4942]]),
 (5000, 20),
 array([[   0,    0,    0, ..., 2031, 5719, 4942],
        [   0,    0,    0, ..., 4054, 2962, 4942],
        [   0,    0,    0, ..., 1490, 4451, 4942],
        ...,
        [   0,    0,    0, ..., 1971, 8927, 4942],
        [   0,    0,    0, ...,  521, 1009, 4942],
        [   0,    0,    0, ..., 3998, 6090, 4942]]),
 (452, 20),
 array([[0, 1, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 1],
        [0, 0, 0, 0, 0, 1],
        ...,
        [1, 0, 0, 0, 0, 0],
        [0, 0, 0, 1, 0, 0],
        [1, 0, 0, 0, 0, 0]], dtype=uint8),
 (5000, 6))

In [26]:
!pip install torchsummary

rnn1 = nn.RNN(300*20, 512, batch_first = True)
zero_state = torch.zeros(1, batch_size, 512)
rnn_output1, hidden = rnn1(flatten, zero_state)

# Embedding

In [27]:
import torch

gpudevice = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using {gpudevice} device in training")

Using cuda device in training


In [28]:
emb = np.array(list(dic.values()))
emb = torch.as_tensor(emb).to(gpudevice)
emb, emb.shape

(tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
           0.0000e+00,  0.0000e+00],
         [ 2.2419e-01, -2.8883e-01,  1.3854e-01,  ...,  1.9312e-01,
          -7.7683e-02, -1.4481e-01],
         [ 1.0000e+00,  1.0000e+00,  1.0000e+00,  ...,  1.0000e+00,
           1.0000e+00,  1.0000e+00],
         ...,
         [ 2.6790e-02, -6.0759e-02,  1.1329e-02,  ..., -4.7001e-01,
          -5.7732e-03, -2.3301e-01],
         [-3.1826e-02, -6.3782e-01, -4.0954e-05,  ..., -1.4163e-01,
          -2.7359e-01,  1.5005e-01],
         [-4.8489e-01,  2.4163e-01, -5.0128e-01,  ..., -7.2599e-01,
           2.1318e-02,  3.4059e-01]], device='cuda:0', dtype=torch.float64),
 torch.Size([9225, 300]))

def create_emb_layer(weights_matrix, trainable=True):
    num_embeddings, embedding_dim = weights_matrix.size()
    emb_layer = nn.Embedding(num_embeddings, embedding_dim)
    emb_layer.load_state_dict({'weight': weights_matrix})
    if trainable:
        emb_layer.weight.requires_grad = True
    else :
        emb_layer.weight.requires_grad = False

    return emb_layer

# Vanilla

import torch
import torch.nn as nn

class VanillaRNN(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super().__init__()
        self.hidden_size = hidden_size
        self.W_hh = nn.Parameter(torch.randn(hidden_size, hidden_size))
        self.W_xh = nn.Parameter(torch.randn(input_size, hidden_size))
        self.W_hy = nn.Parameter(torch.randn(hidden_size, output_size))
        self.bias_h = nn.Parameter(torch.randn(hidden_size))
        self.bias_y = nn.Parameter(torch.randn(output_size))

    def forward(self, x, h=None):
        if h is None:
            h = torch.zeros(x.size(0), self.hidden_size, device=x.device)
        h = h.unsqueeze(1).expand(-1, x.size(1), -1)  # h.shape -> (256,20,hidden_size)
        h = torch.tanh(torch.matmul(x, self.W_xh) + torch.matmul(h, self.W_hh) + self.bias_h)
        y = torch.matmul(h, self.W_hy) + self.bias_y
        y = nn.Softmax(dim=1)(y)
        return y, h
    
    def __repr__(self):
        return f"VanillaRNN(input_size={self.W_xh.shape[0]}, hidden_size={self.hidden_size}, output_size={self.W_hy.shape[1]})"

In [29]:
import torch
import torch.nn as nn

class BatchRNN(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super().__init__()
        self.hidden_size = hidden_size
        self.W_hh = nn.Parameter(torch.randn(hidden_size, hidden_size))   # (512, 512)
        self.W_xh = nn.Parameter(torch.randn(input_size, hidden_size))    # (300, 512)
        self.W_hy = nn.Parameter(torch.randn(hidden_size, output_size))   # (512, 6)
        self.bias_h = nn.Parameter(torch.randn(hidden_size))              # (512)
        #self.bias_y = nn.Parameter(torch.randn(output_size))              # (6)

    def forward(self, x, h=None):
        batch_size, seq_len, input_size = x.size()  # batch_size를 추출합니다.   (256, 20, 300)
        #print(batch_size, seq_len, input_size)
        if h is None:
            #print(" h is None ")
            h = torch.zeros(batch_size, seq_len ,self.hidden_size, device=x.device)
        #print("before h :", h.shape)    
        #h = h.unsqueeze(1).expand(batch_size, seq_len, self.hidden_size)  # h.shape -> (batch_size, seq_len, hidden_size) 이거 없애고 위에 zeros에 seq_len 더해줬음
        #print("h.unsqueeze(1).expand(-1, seq_len, self.hidden_size) : ", h.shape)
        h = torch.tanh(torch.matmul(x, self.W_xh) + torch.matmul(h, self.W_hh) + self.bias_h)  # (256, 20, 300) * (300,512) = (20,512) // (256, 20, 512) * (512, 512)= (20,512)
        y = torch.matmul(h, self.W_hy)# + self.bias_y # (20,512) * (512,6) = (20,6) // + (6)
        #print("matmul : ", y.shape)
        #y = nn.Softmax(dim=2)(y)  # dim=2로 설정하여 시간 축 (seq_len)에 대해 소프트맥스를 적용합니다.
        #print("softmax : ", y.shape)
        return y, h

    def __repr__(self):
        return f"BatchRNN(input_size={self.W_xh.shape[0]}, hidden_size={self.hidden_size}, output_size={self.W_hy.shape[1]})"


In [30]:
import torch
import torch.nn as nn

class DeepRNN(nn.Module):
    def __init__(self, input_size, hidden_size, output_size, num_layers):
        super().__init__()
        self.hidden_size = hidden_size
        self.num_layers = num_layers
        
        # 첫 번째 BatchRNN 레이어
        self.batch_rnn1 = BatchRNN(input_size, hidden_size, hidden_size)   # (300, 128, 128) (input_size, hidden_size, hidden_size)
        
        # 중간에 쌓을 BatchRNN 레이어들
        self.batch_rnns = nn.ModuleList([BatchRNN(hidden_size, hidden_size, 256) for _ in range(num_layers-2)]) # (128, 128, 128)   # (hidden_size,hidden_size,hidden_size)
        
        # 마지막 BatchRNN 레이어
        self.batch_rnn2 = BatchRNN(256, hidden_size, output_size)  # org = (hidden_size, hidden_size, output_size) (128, 128, 512)
        
        self.layer_norm1 = nn.LayerNorm(hidden_size)  # hidden_size
        self.layer_norm2 = nn.LayerNorm(256)  # hidden_size
        self.layer_norm3 = nn.LayerNorm(output_size)
        
        
        
        
        
    def forward(self, x, h=None):
        batch_size, seq_len, input_size = x.size()
        
        # 첫 번째 BatchRNN 레이어를 통과한 결과를 입력으로 사용합니다.
        y, h = self.batch_rnn1(x, h)
        #print("y_rnn1 : ", y.shape)     # (256,20,128)
        y = self.layer_norm1(y)
        
        # 중간에 쌓은 BatchRNN 레이어를 차례대로 통과시킵니다.
        for batch_rnn in self.batch_rnns:
            y, h = batch_rnn(y, h)
            #print("y_rnn2 : ", y.shape)
            y = self.layer_norm2(y)
        
        # 마지막 BatchRNN 레이어를 통과시킨 결과를 반환합니다.
        y, h = self.batch_rnn2(y, h)
        #print("y : ", y.shape)
        #print("h : ", h.shape)
        y = self.layer_norm3(y)
        return y, h
    
    def __repr__(self):
        return f"DeepRNN(input_size={self.batch_rnn1.W_xh.shape[0]}, hidden_size={self.hidden_size}, output_size={self.batch_rnn2.W_hy.shape[1]}, num_layers={self.num_layers})"


In [31]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import torch.utils.data as data_utils
import numpy as np
from torchsummary import summary


batch_size = 256

# 데이터를 Tensor로 변환
X_tensor = torch.tensor(X_train, dtype=torch.long).to(gpudevice)
y_tensor = torch.tensor(y_train, dtype=torch.long).to(gpudevice)

# 데이터를 train set과 validation set으로 나눔
n_samples = X_train.shape[0]
val_size = int(0.2 * n_samples)  # 20%를 validation set으로 사용
train_size = n_samples - val_size

train_indices, val_indices = np.split(np.arange(n_samples), [train_size])

train_data = data_utils.TensorDataset(X_tensor[train_indices], y_tensor[train_indices])
val_data = data_utils.TensorDataset(X_tensor[val_indices], y_tensor[val_indices])

trainloader = data_utils.DataLoader(train_data, batch_size=batch_size, shuffle=True)
val_loader = data_utils.DataLoader(val_data, batch_size=batch_size, shuffle=False)




# 모델 구현
class Textclassifier(nn.Module):
    def __init__(self, input_size, hidden_size, output_size, num_layers, pre_trained): #pre_trained : torch.Size([9225, 300])
        super().__init__()
        #self.emb = create_emb_layer(pre_trained, False)  
        self.emb = pre_trained
        self.rnn = DeepRNN(input_size, hidden_size, output_size, num_layers)
        #self.dropout = nn.Dropout(p=0.2)
        #self.layer_norm = nn.LayerNorm(output_size)
        self.flatten = nn.Flatten(start_dim=1)
        self.fc = nn.Linear(output_size*20, 6)
        self.softmax = nn.Softmax(dim=1)
        

        
    def forward(self, text):

        embedded = torch.tensor(self.emb[text], dtype = torch.float32)     # (batch_size,20,300)
        
        #print("embedded : ", embedded.shape)
        
        y,_ = self.rnn(embedded)#, h0)#, self.zero_state)
        #y = self.dropout(y)
        
        #print("y : ", y.shape)
        
        #norm = self.layer_norm(y)
        
        flatten = self.flatten(y)
        
        #print("flatten : ", flatten)

        fc_output = self.fc(flatten)
        
        #print("fc_output : ", fc_output.shape)
        
        softmax_output = self.softmax(fc_output)
        
        #print("softmax_output : ", softmax_output.shape)
        
        nn.utils.clip_grad_norm_(self.parameters(), max_norm=1.0)
        
        return softmax_output

model = Textclassifier(input_size = 300, hidden_size = 512, output_size= 128, num_layers = 3, pre_trained = emb).to(gpudevice)  ## emb is embedding vector
#print(model.state_dict())     ### 초기 가중치 확인

print(model)

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001, weight_decay=0.0001, betas=(0.9, 0.999))


Textclassifier(
  (rnn): DeepRNN(input_size=300, hidden_size=512, output_size=128, num_layers=3)
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (fc): Linear(in_features=2560, out_features=6, bias=True)
  (softmax): Softmax(dim=1)
)


In [32]:
num_epochs = 2000

for epoch in range(num_epochs):
    running_loss = 0.0
    for i, data in enumerate(trainloader, 0):
        inputs, labels = data
        
        #print("inputs.shape : ", inputs.shape)   # (batch size, embedding_size) 
        #print("labels.shape : ", labels.shape)

        optimizer.zero_grad()

        outputs = model(inputs).to(gpudevice)
        
        #print(outputs.shape)
        
        loss = criterion(outputs.float(), labels.float())
        loss.backward()

        optimizer.step()

        running_loss += loss.item()

    # Calculate accuracy on validation set
    correct = 0
    total = 0
    with torch.no_grad():
        for data in val_loader:
            inputs, labels = data
            
            #print("val-inputs.shape : ", inputs.shape)   # (batch size, embedding_size) 
            #print("val-labels.shape : ", labels.shape)
            
            outputs = model(inputs).to(gpudevice)
            
            _, predicted = torch.max(outputs, 1)
            _, labels = torch.max(labels, 1)
            
            #print(predicted)
            #print(predicted.shape)
            
            
    
            #print("predicted.shape : ", predicted.shape)
            #print("labels.shape : ", labels.shape)
            
            total += labels.size(0)
            correct += (predicted == labels).sum().item()

    accuracy = 100 * correct / total

    print('[%d] loss: %.3f, accuracy: %.3f%%' % (epoch + 1, running_loss, accuracy))
    #for name, param in model.named_parameters():
    #    if param.requires_grad:
    #        print(name, param.data)
    running_loss = 0.0
    
print('Finished Training')

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:49: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).


[1] loss: 27.496, accuracy: 38.700%
[2] loss: 25.710, accuracy: 46.500%
[3] loss: 24.608, accuracy: 47.400%
[4] loss: 23.885, accuracy: 48.400%
[5] loss: 23.432, accuracy: 51.700%
[6] loss: 22.556, accuracy: 57.700%
[7] loss: 21.694, accuracy: 59.000%
[8] loss: 21.126, accuracy: 60.300%
[9] loss: 20.717, accuracy: 60.200%
[10] loss: 20.386, accuracy: 60.600%
[11] loss: 20.156, accuracy: 61.500%
[12] loss: 19.960, accuracy: 61.800%
[13] loss: 19.812, accuracy: 62.100%
[14] loss: 19.723, accuracy: 62.000%
[15] loss: 19.668, accuracy: 62.900%
[16] loss: 19.620, accuracy: 62.700%
[17] loss: 19.578, accuracy: 63.500%
[18] loss: 19.529, accuracy: 63.400%
[19] loss: 19.104, accuracy: 63.900%
[20] loss: 18.561, accuracy: 67.400%
[21] loss: 18.104, accuracy: 68.000%
[22] loss: 17.705, accuracy: 69.000%
[23] loss: 17.423, accuracy: 69.800%
[24] loss: 17.309, accuracy: 70.000%
[25] loss: 17.217, accuracy: 70.900%
[26] loss: 17.169, accuracy: 71.200%
[27] loss: 17.142, accuracy: 71.000%
[28] loss:

In [33]:
X_test_tensor = torch.tensor(X_test, dtype=torch.long).to(gpudevice)
with torch.no_grad():
    output = model(X_test_tensor)
    _, predicted_labels = torch.max(output, 1)
    
predicted_labels

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:49: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).


tensor([5, 3, 4, 1, 3, 5, 1, 5, 1, 1, 1, 4, 3, 0, 0, 1, 4, 3, 0, 0, 1, 1, 1, 0,
        5, 0, 3, 5, 0, 5, 3, 1, 3, 5, 3, 5, 1, 5, 5, 1, 5, 1, 0, 3, 3, 5, 1, 1,
        1, 3, 4, 3, 1, 4, 3, 0, 1, 1, 5, 5, 4, 1, 0, 0, 1, 3, 3, 2, 4, 5, 3, 4,
        4, 3, 0, 5, 5, 4, 1, 3, 0, 0, 1, 1, 3, 3, 1, 1, 0, 2, 0, 1, 5, 0, 1, 0,
        1, 0, 3, 3, 1, 4, 0, 5, 3, 0, 2, 0, 0, 5, 4, 3, 3, 3, 3, 1, 1, 1, 3, 4,
        0, 3, 1, 3, 5, 1, 0, 0, 3, 4, 3, 4, 1, 1, 0, 5, 0, 1, 0, 5, 1, 5, 5, 0,
        3, 4, 0, 4, 2, 1, 1, 1, 4, 5, 4, 5, 1, 1, 5, 1, 5, 3, 0, 5, 5, 1, 3, 5,
        1, 3, 1, 3, 0, 4, 4, 1, 0, 4, 5, 0, 1, 4, 0, 1, 3, 1, 1, 0, 0, 5, 1, 0,
        4, 3, 0, 5, 3, 5, 0, 1, 3, 0, 0, 3, 0, 0, 1, 3, 4, 0, 1, 0, 3, 1, 3, 5,
        4, 5, 4, 5, 0, 3, 1, 1, 4, 1, 1, 5, 4, 0, 1, 1, 0, 1, 4, 3, 1, 3, 3, 3,
        5, 1, 3, 3, 0, 2, 4, 3, 5, 3, 5, 3, 1, 4, 1, 1, 1, 0, 4, 1, 4, 0, 3, 3,
        5, 4, 1, 0, 0, 3, 0, 1, 3, 1, 4, 4, 0, 3, 4, 0, 3, 3, 1, 1, 0, 3, 5, 5,
        0, 4, 1, 0, 0, 1, 5, 1, 2, 5, 0,

In [34]:
predicted_labels = predicted_labels.detach().cpu().numpy()
index_list = []
for i in range(0,len(predicted_labels)):
    index_list.append(f"S{i}")
    
prediction = pd.DataFrame(columns=['ID', 'label'])

prediction["ID"] = index_list
prediction["label"] = predicted_labels

prediction = prediction.reset_index(drop=True)

prediction.to_csv('20221119_하준서_sent_class.pred.csv', index = False)

#index_list
prediction

ID  label
0      S0      5
1      S1      3
2      S2      4
3      S3      1
4      S4      3
..    ...    ...
447  S447      0
448  S448      0
449  S449      3
450  S450      1
451  S451      0

[452 rows x 2 columns]

# Origin

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import torch.utils.data as data_utils
import numpy as np
from torchsummary import summary


batch_size = 256

# 데이터를 Tensor로 변환
X_tensor = torch.tensor(X_train, dtype=torch.long)
y_tensor = torch.tensor(y_train, dtype=torch.long)

# 데이터를 train set과 validation set으로 나눔
n_samples = X_train.shape[0]
val_size = int(0.1 * n_samples)  # 20%를 validation set으로 사용
train_size = n_samples - val_size

train_indices, val_indices = np.split(np.arange(n_samples), [train_size])

train_data = data_utils.TensorDataset(X_tensor[train_indices], y_tensor[train_indices])
val_data = data_utils.TensorDataset(X_tensor[val_indices], y_tensor[val_indices])

trainloader = data_utils.DataLoader(train_data, batch_size=batch_size, shuffle=True)
val_loader = data_utils.DataLoader(val_data, batch_size=batch_size, shuffle=False)




# 모델 구현
class RNN(nn.Module):
    def __init__(self, num_embeddings, embedding_dim, hidden_dim, output_dim):
        super().__init__()
        self.embedding = nn.Embedding(num_embeddings, embedding_dim)
        #self.flatten = nn.Flatten()
        self.rnn1 = nn.RNN(embedding_dim*20, hidden_dim, batch_first = True)
        self.rnn2 = nn.RNN(hidden_dim, hidden_dim, batch_first = True)
        self.rnn3 = nn.RNN(hidden_dim, hidden_dim, batch_first = True)
        self.layer_norm = nn.LayerNorm(hidden_dim)
        self.fc = nn.Linear(hidden_dim, output_dim)
        self.log_softmax = nn.LogSoftmax(dim=1)
        
        # zero vector로 초기 상태 설정
        #self.zero_state = torch.zeros(1, hidden_dim)
        
    def forward(self, text):
        embedded = self.embedding(text)
        flatten = self.flatten(embedded)
        
        rnn_output1, hidden = self.rnn1(flatten)#, self.zero_state)
        rnn_output2, hidden = self.rnn2(rnn_output1)#, self.zero_state)
        rnn_output3, hidden = self.rnn3(rnn_output2)#, self.zero_state)
        
        norm = self.layer_norm(rnn_output3)


        #hidden = torch.tanh(output)
        fc_output = self.fc(norm)
        softmax_output = self.log_softmax(fc_output)
        
        #nn.utils.clip_grad_norm_(self.parameters(), max_norm=1.0)
        

        
        return fc_output

model = RNN(num_embeddings=len(dic),embedding_dim = 300, hidden_dim=512, output_dim=y_train.shape[1])
#print(model.state_dict())     ### 초기 가중치 확인

print(model)

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.00001, weight_decay=0.0001, betas=(0.9, 0.999))


num_epochs = 2

for epoch in range(num_epochs):
    running_loss = 0.0
    for i, data in enumerate(trainloader, 0):
        inputs, labels = data
        
        #print(inputs.shape)
        #print(labels.shape)

        optimizer.zero_grad()

        outputs = model(inputs)
        
        #print(outputs)
        
        loss = criterion(outputs.float(), labels.float())
        loss.backward()

        optimizer.step()

        running_loss += loss.item()

    # Calculate accuracy on validation set
    correct = 0
    total = 0
    with torch.no_grad():
        for data in val_loader:
            inputs, labels = data
            outputs = model(inputs)
            _, predicted = torch.max(outputs, 1)
            _, labels = torch.max(labels, 1)          # convert word to id
            #print(predicted)
            #print(labels)
            #print(torch.max(labels, 1))
            total += labels.size(0)
            correct += (predicted == labels).sum().item()

    accuracy = 100 * correct / total

    print('[%d] loss: %.3f, accuracy: %.3f%%' % (epoch + 1, running_loss, accuracy))
    #for name, param in model.named_parameters():
    #    if param.requires_grad:
    #        print(name, param.data)
    running_loss = 0.0
    
print('Finished Training')

# NEW_algorithm